# Generated by Django 4.0.3 on 2023-11-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
