# Generated by Django 4.0.3 on 2024-03-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='watchcustomization',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='watch_customization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horofixapp.watchcustomization'),
        ),
    ]
