# Generated by Django 5.0.3 on 2024-04-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
