# Generated by Django 4.2.7 on 2023-11-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer',
            new_name='user',
        ),
    ]
