# Generated by Django 5.0.3 on 2024-04-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True, unique=True)),
                ('watch_modelnumber', models.CharField(max_length=255, null=True)),
                ('watch_serial_number', models.CharField(max_length=255, null=True, unique=True)),
                ('watch_description', models.TextField()),
                ('watch_image', models.ImageField(blank=True, null=True, upload_to='watch_images/')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_sale_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Unisex', 'Unisex')], default=None, max_length=10)),
                ('stock', models.PositiveIntegerField(default=1, null=True)),
                ('ratings', models.IntegerField(default=0)),
                ('warranty', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], default='Placed', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customwatch')),
            ],
        ),
        migrations.AddField(
            model_name='customorder',
            name='products',
            field=models.ManyToManyField(through='horofixapp.CustomOrderItem', to='horofixapp.customwatch'),
        ),
        migrations.CreateModel(
            name='CustomizationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strap_material', models.CharField(blank=True, max_length=100, null=True)),
                ('strap_color', models.CharField(blank=True, max_length=50, null=True)),
                ('dial_color', models.CharField(blank=True, max_length=50, null=True)),
                ('case_material', models.CharField(blank=True, max_length=100, null=True)),
                ('case_color', models.CharField(blank=True, max_length=50, null=True)),
                ('engraving_text', models.CharField(blank=True, max_length=255, null=True)),
                ('engraving_font', models.CharField(blank=True, max_length=50, null=True)),
                ('engraving_location', models.CharField(blank=True, max_length=100, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customwatch')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customwatch')),
            ],
        ),
        migrations.AddField(
            model_name='customcart',
            name='products',
            field=models.ManyToManyField(through='horofixapp.CustomCartItem', to='horofixapp.customwatch'),
        ),
    ]
