# Generated by Django 4.2.7 on 2024-02-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
