# Generated by Django 4.0.3 on 2023-11-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
