# Generated by Django 4.2.7 on 2023-11-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='horofixapp.deliveryteam'),
            preserve_default=False,
        ),
    ]
