# Generated by Django 4.2.7 on 2024-02-09 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialization', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_technician',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('VENDOR', 'Vendor'), ('DELIVERYTEAM', 'Deliveryteam'), ('CUSTOMER', 'Customer'), ('TECHNICIAN', ' Technician')], default='CUSTOMER', max_length=20, null=True),
        ),
    ]
