# Generated by Django 5.0.3 on 2024-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0003_customwatch_customcart_customorder_customorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
