# Generated by Django 4.0.3 on 2023-09-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0003_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
