# Generated by Django 4.2.7 on 2024-02-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0003_technician_customuser_is_technician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='specialization',
        ),
    ]
