# Generated by Django 4.2.7 on 2023-11-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0003_order_delivery_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_team',
        ),
    ]
