# Generated by Django 4.2.7 on 2024-02-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0004_rename_watch_model_watchproduct_watch_modelnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchrepairrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchrepairrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
