# Generated by Django 4.2.7 on 2023-11-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0004_remove_order_delivery_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryteam',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deliveryteam',
            name='id_proof_number',
        ),
        migrations.AddField(
            model_name='deliveryteam',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
