# Generated by Django 5.0.3 on 2024-04-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0004_orderitem_delivery_address_orderitem_lat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watch',
        ),
        migrations.RemoveField(
            model_name='customcart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='customcartitem',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customcart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='horofixapp.customcartitem'),
        ),
        migrations.AddField(
            model_name='customcartitem',
            name='customization_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customizationdetail'),
        ),
    ]
