# Generated by Django 4.2.7 on 2024-02-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0004_remove_repairpayment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchproduct',
            name='watch_modelnumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
