# Generated by Django 5.0.3 on 2024-04-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0005_delete_watch_remove_customcart_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='customcartitem',
            name='customization_detail',
        ),
        migrations.RemoveField(
            model_name='customcartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='products',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='CustomCart',
        ),
        migrations.DeleteModel(
            name='CustomCartItem',
        ),
        migrations.DeleteModel(
            name='CustomOrder',
        ),
        migrations.DeleteModel(
            name='CustomOrderItem',
        ),
    ]
