# Generated by Django 4.2.7 on 2024-02-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0005_alter_watchproduct_watch_modelnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchrepairrequest',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='watchrepairrequest',
            name='issue_types',
            field=models.ManyToManyField(to='horofixapp.watchrepairservice'),
        ),
    ]
