# Generated by Django 4.0.3 on 2023-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0006_alter_watchproduct_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchproduct',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
