# Generated by Django 4.2.7 on 2023-11-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0006_alter_deliveryteam_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
