# Generated by Django 4.2.7 on 2024-02-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0006_remove_watchrepairrequest_issue_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchrepairrequest',
            name='issue_types',
        ),
        migrations.AddField(
            model_name='watchrepairrequest',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horofixapp.watchrepairservice'),
        ),
    ]
