# Generated by Django 4.0.3 on 2023-09-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
