# Generated by Django 4.0.3 on 2023-11-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0007_watchproduct_in_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='WatchProduct',
        ),
    ]
