# Generated by Django 5.0.3 on 2024-04-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0007_custorder_carti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='custorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='custorder',
            name='updated_by_delivery_boy',
        ),
        migrations.RemoveField(
            model_name='custorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartI',
        ),
        migrations.DeleteModel(
            name='CustOrder',
        ),
    ]
