# Generated by Django 4.2.7 on 2024-02-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0008_remove_watchrepairrequest_issue_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchrepairrequest',
            old_name='issue_types',
            new_name='issue_type',
        ),
    ]
