# Generated by Django 4.0.3 on 2023-11-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0008_delete_cartproduct_delete_watchproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('watch_description', models.TextField()),
                ('watch_image', models.ImageField(blank=True, null=True, upload_to='watch_images/')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_sale_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default=None, max_length=10)),
                ('stock', models.PositiveIntegerField(default=1, null=True)),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=12)),
            ],
        ),
    ]
