# Generated by Django 4.2.7 on 2024-02-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0009_rename_issue_types_watchrepairrequest_issue_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchrepairrequest',
            old_name='issue_type',
            new_name='issue_types',
        ),
    ]
