# Generated by Django 4.0.3 on 2023-11-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0009_watchproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchProduct',
        ),
    ]
