# Generated by Django 4.0.3 on 2023-10-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0010_customer_profile_delete_customerprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Profile',
            new_name='CustomerProfile',
        ),
    ]
