# Generated by Django 5.0.3 on 2024-04-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0011_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customizationdetail'),
        ),
        migrations.AlterField(
            model_name='customizationdetail',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horofixapp.watchproduct'),
        ),
    ]
