# Generated by Django 4.0.3 on 2023-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0011_watchproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchproduct',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='watchproduct',
            name='product_status',
        ),
        migrations.AddField(
            model_name='watchproduct',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=12),
        ),
    ]
