# Generated by Django 4.0.3 on 2023-10-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0011_rename_customer_profile_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='first_name',
            new_name='name',
        ),
    ]
