# Generated by Django 4.0.3 on 2023-11-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0013_addtocart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='date_added',
        ),
    ]
