# Generated by Django 4.2.7 on 2024-03-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0014_customizedwatch_watchcomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strap_material', models.CharField(choices=[('leather', 'Leather'), ('metal', 'Metal'), ('rubber', 'Rubber'), ('nylon', 'Nylon')], max_length=50)),
                ('strap_color', models.CharField(max_length=50)),
                ('watch_color', models.CharField(max_length=50)),
                ('dial_shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('digital', 'Digital')], max_length=50)),
                ('watch_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('include_date', models.BooleanField(default=False)),
                ('watch_hands_color', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('black', 'Black')], max_length=50)),
                ('include_backlight', models.BooleanField(default=False)),
                ('owner_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customizedwatchcomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='customizedwatchcomponent',
            name='customized_watch',
        ),
        migrations.DeleteModel(
            name='CustomizedWatch',
        ),
        migrations.DeleteModel(
            name='CustomizedWatchComponent',
        ),
        migrations.DeleteModel(
            name='WatchComponent',
        ),
    ]
