# Generated by Django 5.0.3 on 2024-04-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0014_deliveryassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customization',
        ),
        migrations.DeleteModel(
            name='CustomizationDetail',
        ),
    ]
