# Generated by Django 4.0.3 on 2023-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0014_customerprofile_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
