# Generated by Django 4.2.7 on 2024-03-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0015_watchcustomization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchcustomization',
            name='include_backlight',
        ),
        migrations.RemoveField(
            model_name='watchcustomization',
            name='include_date',
        ),
    ]
