# Generated by Django 5.0.3 on 2024-04-08 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0015_remove_shoppingcartitem_customization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strap_material', models.CharField(blank=True, max_length=100, null=True)),
                ('strap_color', models.CharField(blank=True, max_length=50, null=True)),
                ('dial_color', models.CharField(blank=True, max_length=50, null=True)),
                ('case_material', models.CharField(blank=True, max_length=100, null=True)),
                ('case_color', models.CharField(blank=True, max_length=50, null=True)),
                ('engraving_text', models.CharField(blank=True, max_length=255, null=True)),
                ('engraving_font', models.CharField(blank=True, max_length=50, null=True)),
                ('engraving_location', models.CharField(blank=True, max_length=100, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customwatch')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customizationdetail'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customizationdetail'),
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='customization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='horofixapp.customizationdetail'),
        ),
    ]
