# Generated by Django 4.2.7 on 2024-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0016_remove_watchcustomization_include_backlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchcustomization',
            name='watch_image',
            field=models.ImageField(default='watch_images/default_image.jpg', null=True, upload_to='watch_images/'),
        ),
    ]
