# Generated by Django 4.0.3 on 2023-10-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0016_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=255)),
                ('watch_description', models.TextField()),
                ('watch_image', models.ImageField(upload_to='watch_images/')),
            ],
        ),
    ]
