# Generated by Django 4.0.3 on 2023-10-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0018_alter_watchproduct_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchProduct',
        ),
    ]
