# Generated by Django 4.2.5 on 2023-11-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0019_cartitem_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingInformation',
        ),
    ]
