# Generated by Django 4.2.5 on 2023-10-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0020_watchproduct_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
