# Generated by Django 5.0.3 on 2024-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0021_order_delivery_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryteam',
            name='city',
        ),
        migrations.AddField(
            model_name='deliveryteam',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
