# Generated by Django 4.2.5 on 2023-11-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0024_orderitem_order_date_orderitem_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment Successful', 'Payment Successful')], default='Pending', max_length=20),
        ),
    ]
