# Generated by Django 4.2.5 on 2023-11-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0026_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
