# Generated by Django 4.2.7 on 2023-11-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0027_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchproduct',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
