# Generated by Django 4.2.5 on 2023-10-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0028_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchproduct',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Men', max_length=10),
        ),
    ]
