# Generated by Django 4.2.5 on 2023-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0029_watchproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchproduct',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10),
        ),
    ]
