# Generated by Django 4.2.7 on 2023-11-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0030_order_delivered_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_location',
        ),
    ]
