# Generated by Django 4.2.7 on 2023-11-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0031_remove_order_delivered_remove_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Delivery Boy', editable=False, max_length=100, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('id_proof_number', models.CharField(default='', max_length=100, null=True)),
                ('qualification', models.CharField(default='', max_length=100, null=True)),
                ('emergency_name', models.CharField(default='', max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='deliveryboy_profile/')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
