# Generated by Django 4.2.7 on 2023-11-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0032_deliveryboy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='emergency_name',
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='emergency_contact_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
