# Generated by Django 4.2.7 on 2023-11-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0033_remove_deliveryboy_emergency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='emergency_contact_number',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
