# Generated by Django 4.2.7 on 2023-11-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horofixapp', '0036_deliveryboy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='id_proof_number',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='qualification',
        ),
    ]
